root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/app ./cmd/server "
bin = "bin/app"
include_ext = ["go"]
exclude_dir = ["assets", "tmp", "vendor"]
delay = 1000                                # ms
