name: go-app
services:
  go-app_db:
    container_name: go-app_db
    image: postgres:17
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - go-app_db:/var/lib/postgresql/data

  go-app_redis:
    container_name: go-app_cache
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - go-app_redis:/data

volumes:
  go-app_db:
    name: go-app-db
  go-app_redis:
    name: go-app-redis
